import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1773825750988 implements MigrationInterface {
    name = 'InitSchema1773825750988'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "sys_branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "code" character varying(50) NOT NULL, "name" character varying(150) NOT NULL, "currency" character varying(10) NOT NULL, "timezone" character varying(50) NOT NULL, CONSTRAINT "UQ_4db5fa3ad8a01c18470701cb8e3" UNIQUE ("code"), CONSTRAINT "PK_c088ff0b6f8d7c43bef377a2525" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sls_quotations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "branch_id" uuid NOT NULL, "client_id" uuid NOT NULL, "pm_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "total_estimated_hours" numeric(10,2) NOT NULL, "total_amount" numeric(15,2) NOT NULL, "status" character varying(50) NOT NULL, "valid_until" date NOT NULL, "file_url" character varying(255), CONSTRAINT "PK_853f02e8dca20f2bff4f2cda777" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sls_contracts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "quotation_id" uuid NOT NULL, "contract_number" character varying(100) NOT NULL, "file_url" character varying(255) NOT NULL, "document_hash" character varying(255) NOT NULL, "status" character varying(50) NOT NULL, CONSTRAINT "UQ_10b2bcac3a88541a1dde28a3c39" UNIQUE ("contract_number"), CONSTRAINT "PK_904ba0271616c45a6c059359ff5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "prj_projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "quotation_id" uuid, "contract_id" uuid, "branch_id" uuid, "pm_id" uuid, "name" character varying(255) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'PENDING', "is_alerted_80" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_dba7ee8ae8c783b67a03b028199" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "prj_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "project_id" uuid NOT NULL, "assignee_id" uuid, "title" character varying(255) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'TODO', "estimated_hours" numeric(8,2), "risk_buffer_percent" numeric(5,2), "rejection_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_e59c8a52f2c2b1d77f27ec07766" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fin_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "project_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "invoice_number" character varying(100) NOT NULL, "subtotal_amount" numeric(15,2) NOT NULL, "vat_amount" numeric(15,2) NOT NULL, "total_amount" numeric(15,2) NOT NULL, "issue_date" date NOT NULL, "due_date" date NOT NULL, "status" character varying(50) NOT NULL, CONSTRAINT "UQ_780cfecb649a606343ecc5913e2" UNIQUE ("invoice_number"), CONSTRAINT "PK_a9f1a9f2ccf6e9a6854c7048184" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tms_timesheets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "task_id" uuid NOT NULL, "user_id" uuid NOT NULL, "log_date" date NOT NULL, "logged_hours" numeric(5,2) NOT NULL, "work_type" character varying(50) NOT NULL, "snapshot_price" numeric(15,2) NOT NULL, "snapshot_billable_price" numeric(15,2) NOT NULL, "approval_status" character varying(50) NOT NULL, "approved_by" uuid, "reject_reason" text, "invoice_id" uuid, CONSTRAINT "PK_972d277270e28002b7933a7e291" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sys_notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "user_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_f2357ca7795fc84fa12144daf87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sys_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "user_id" uuid, "actor_type" character varying(20) NOT NULL, "action" character varying(50) NOT NULL, "table_name" character varying(50) NOT NULL, "record_id" uuid NOT NULL, "old_value" jsonb, "new_value" jsonb, CONSTRAINT "PK_a73a193cd9735f1bd1878b249ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "prj_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "project_id" uuid NOT NULL, "user_id" uuid NOT NULL, "assigned_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_6827cb23b35e2e4f4a275430789" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "prj_baselines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "project_id" uuid NOT NULL, "version_name" character varying(50) NOT NULL, "total_estimated_hours" numeric(10,2) NOT NULL, "snapshot_data" jsonb NOT NULL, CONSTRAINT "PK_6379f3878fd5dd849108e2d0432" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sys_digital_signatures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "contract_id" uuid NOT NULL, "user_id" uuid NOT NULL, "provider" character varying(50) NOT NULL, "cert_serial_number" character varying(255) NOT NULL, "signature_value" text NOT NULL, "signed_at" TIMESTAMP NOT NULL, CONSTRAINT "PK_6b6c032a8372f5c2cfa158c7773" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "auth_credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "user_id" uuid NOT NULL, "credential_id" character varying(255) NOT NULL, "public_key" text NOT NULL, "sign_counter" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_a79e220aac1cdd4fa1d627d1254" UNIQUE ("credential_id"), CONSTRAINT "PK_90fdced0865b5f15586e7cd3b25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fin_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "invoice_id" uuid NOT NULL, "payment_method" character varying(50) NOT NULL, "paid_amount" numeric(15,2) NOT NULL, "payment_date" TIMESTAMP NOT NULL, "reference_code" character varying(255), CONSTRAINT "PK_14e9543579a307d84043d28165b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "csk_tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, "updated_by" uuid, "project_id" uuid NOT NULL, "client_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "ticket_type" character varying(50) NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'OPEN', "blame_user_id" uuid, CONSTRAINT "PK_9535536c3eaf71d321a40a2952a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "passwordHash"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "branch_id" uuid`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "full_name" character varying(150)`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "hourly_rate" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "actor_type" character varying(20) NOT NULL DEFAULT 'HUMAN'`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP CONSTRAINT "UQ_0692f810e8926469bec26da0d99"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD CONSTRAINT "UQ_0692f810e8926469bec26da0d99" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."iam_users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "role" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD CONSTRAINT "FK_7b69a643c05891644be11a32d7e" FOREIGN KEY ("branch_id") REFERENCES "sys_branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sls_quotations" ADD CONSTRAINT "FK_9013c17bdbd80d90a6c37519b93" FOREIGN KEY ("branch_id") REFERENCES "sys_branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sls_quotations" ADD CONSTRAINT "FK_4de01333d0659f11af8dc9ecc85" FOREIGN KEY ("client_id") REFERENCES "iam_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sls_quotations" ADD CONSTRAINT "FK_559de22962a53b39e589f50c5c1" FOREIGN KEY ("pm_id") REFERENCES "iam_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sls_contracts" ADD CONSTRAINT "FK_f8936f594cbe9985b10a0646897" FOREIGN KEY ("quotation_id") REFERENCES "sls_quotations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prj_projects" ADD CONSTRAINT "FK_56f9c5098214389ec0905627c22" FOREIGN KEY ("quotation_id") REFERENCES "sls_quotations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prj_projects" ADD CONSTRAINT "FK_66af94e4ba5d2a834c4e82969ac" FOREIGN KEY ("contract_id") REFERENCES "sls_contracts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prj_projects" ADD CONSTRAINT "FK_f0df1b6bec4abd0881a8f0f08b6" FOREIGN KEY ("branch_id") REFERENCES "sys_branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prj_projects" ADD CONSTRAINT "FK_45b1df459bd2bae71060756da01" FOREIGN KEY ("pm_id") REFERENCES "iam_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prj_tasks" ADD CONSTRAINT "FK_62698b295383c672c4a7ac816bc" FOREIGN KEY ("project_id") REFERENCES "prj_projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prj_tasks" ADD CONSTRAINT "FK_b1aeb6d9cd73ec6c737c4d4d8a7" FOREIGN KEY ("assignee_id") REFERENCES "iam_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_invoices" ADD CONSTRAINT "FK_7ea49a8178bb7e00982dfff257b" FOREIGN KEY ("project_id") REFERENCES "prj_projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_invoices" ADD CONSTRAINT "FK_44e08a8625a644c0dff79b64929" FOREIGN KEY ("branch_id") REFERENCES "sys_branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tms_timesheets" ADD CONSTRAINT "FK_ac91365463f3ed5e34bd2466ad9" FOREIGN KEY ("task_id") REFERENCES "prj_tasks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tms_timesheets" ADD CONSTRAINT "FK_4892699fad4b226239a9d4957e9" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tms_timesheets" ADD CONSTRAINT "FK_b7543f2d4db398b710e4930126c" FOREIGN KEY ("approved_by") REFERENCES "iam_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tms_timesheets" ADD CONSTRAINT "FK_b816e944fb3d7085d92a7ed223b" FOREIGN KEY ("invoice_id") REFERENCES "fin_invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sys_notifications" ADD CONSTRAINT "FK_28fe53ec526297ba48e900e8a0d" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sys_audit_logs" ADD CONSTRAINT "FK_e5063b65286a9bdeed1bcf26ba0" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prj_members" ADD CONSTRAINT "FK_38fd186f46f96d3c4173b641589" FOREIGN KEY ("project_id") REFERENCES "prj_projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prj_members" ADD CONSTRAINT "FK_dfc7796d03570a8731c08d4ff3a" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prj_baselines" ADD CONSTRAINT "FK_84121a86a04017087a1ec18f1e9" FOREIGN KEY ("project_id") REFERENCES "prj_projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sys_digital_signatures" ADD CONSTRAINT "FK_4f0c896d74e8db796f2f96cf17c" FOREIGN KEY ("contract_id") REFERENCES "sls_contracts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sys_digital_signatures" ADD CONSTRAINT "FK_baf744b0f2729d665fb202169ff" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" ADD CONSTRAINT "FK_8555dcc06a7fc7fa9844a5e7245" FOREIGN KEY ("user_id") REFERENCES "iam_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fin_payments" ADD CONSTRAINT "FK_fd05d8db4f7247ea27bc9848d32" FOREIGN KEY ("invoice_id") REFERENCES "fin_invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "csk_tickets" ADD CONSTRAINT "FK_553825785c421cfe1008642d76a" FOREIGN KEY ("project_id") REFERENCES "prj_projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "csk_tickets" ADD CONSTRAINT "FK_4d204fd503f2f7bc31d26866cad" FOREIGN KEY ("client_id") REFERENCES "iam_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "csk_tickets" ADD CONSTRAINT "FK_37dd45e32b5cc398ddb9b4341f0" FOREIGN KEY ("blame_user_id") REFERENCES "iam_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "csk_tickets" DROP CONSTRAINT "FK_37dd45e32b5cc398ddb9b4341f0"`);
        await queryRunner.query(`ALTER TABLE "csk_tickets" DROP CONSTRAINT "FK_4d204fd503f2f7bc31d26866cad"`);
        await queryRunner.query(`ALTER TABLE "csk_tickets" DROP CONSTRAINT "FK_553825785c421cfe1008642d76a"`);
        await queryRunner.query(`ALTER TABLE "fin_payments" DROP CONSTRAINT "FK_fd05d8db4f7247ea27bc9848d32"`);
        await queryRunner.query(`ALTER TABLE "auth_credentials" DROP CONSTRAINT "FK_8555dcc06a7fc7fa9844a5e7245"`);
        await queryRunner.query(`ALTER TABLE "sys_digital_signatures" DROP CONSTRAINT "FK_baf744b0f2729d665fb202169ff"`);
        await queryRunner.query(`ALTER TABLE "sys_digital_signatures" DROP CONSTRAINT "FK_4f0c896d74e8db796f2f96cf17c"`);
        await queryRunner.query(`ALTER TABLE "prj_baselines" DROP CONSTRAINT "FK_84121a86a04017087a1ec18f1e9"`);
        await queryRunner.query(`ALTER TABLE "prj_members" DROP CONSTRAINT "FK_dfc7796d03570a8731c08d4ff3a"`);
        await queryRunner.query(`ALTER TABLE "prj_members" DROP CONSTRAINT "FK_38fd186f46f96d3c4173b641589"`);
        await queryRunner.query(`ALTER TABLE "sys_audit_logs" DROP CONSTRAINT "FK_e5063b65286a9bdeed1bcf26ba0"`);
        await queryRunner.query(`ALTER TABLE "sys_notifications" DROP CONSTRAINT "FK_28fe53ec526297ba48e900e8a0d"`);
        await queryRunner.query(`ALTER TABLE "tms_timesheets" DROP CONSTRAINT "FK_b816e944fb3d7085d92a7ed223b"`);
        await queryRunner.query(`ALTER TABLE "tms_timesheets" DROP CONSTRAINT "FK_b7543f2d4db398b710e4930126c"`);
        await queryRunner.query(`ALTER TABLE "tms_timesheets" DROP CONSTRAINT "FK_4892699fad4b226239a9d4957e9"`);
        await queryRunner.query(`ALTER TABLE "tms_timesheets" DROP CONSTRAINT "FK_ac91365463f3ed5e34bd2466ad9"`);
        await queryRunner.query(`ALTER TABLE "fin_invoices" DROP CONSTRAINT "FK_44e08a8625a644c0dff79b64929"`);
        await queryRunner.query(`ALTER TABLE "fin_invoices" DROP CONSTRAINT "FK_7ea49a8178bb7e00982dfff257b"`);
        await queryRunner.query(`ALTER TABLE "prj_tasks" DROP CONSTRAINT "FK_b1aeb6d9cd73ec6c737c4d4d8a7"`);
        await queryRunner.query(`ALTER TABLE "prj_tasks" DROP CONSTRAINT "FK_62698b295383c672c4a7ac816bc"`);
        await queryRunner.query(`ALTER TABLE "prj_projects" DROP CONSTRAINT "FK_45b1df459bd2bae71060756da01"`);
        await queryRunner.query(`ALTER TABLE "prj_projects" DROP CONSTRAINT "FK_f0df1b6bec4abd0881a8f0f08b6"`);
        await queryRunner.query(`ALTER TABLE "prj_projects" DROP CONSTRAINT "FK_66af94e4ba5d2a834c4e82969ac"`);
        await queryRunner.query(`ALTER TABLE "prj_projects" DROP CONSTRAINT "FK_56f9c5098214389ec0905627c22"`);
        await queryRunner.query(`ALTER TABLE "sls_contracts" DROP CONSTRAINT "FK_f8936f594cbe9985b10a0646897"`);
        await queryRunner.query(`ALTER TABLE "sls_quotations" DROP CONSTRAINT "FK_559de22962a53b39e589f50c5c1"`);
        await queryRunner.query(`ALTER TABLE "sls_quotations" DROP CONSTRAINT "FK_4de01333d0659f11af8dc9ecc85"`);
        await queryRunner.query(`ALTER TABLE "sls_quotations" DROP CONSTRAINT "FK_9013c17bdbd80d90a6c37519b93"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP CONSTRAINT "FK_7b69a643c05891644be11a32d7e"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."iam_users_role_enum" AS ENUM('USER', 'ADMIN', 'MANAGER')`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "role" "public"."iam_users_role_enum" NOT NULL DEFAULT 'USER'`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP CONSTRAINT "UQ_0692f810e8926469bec26da0d99"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD CONSTRAINT "UQ_0692f810e8926469bec26da0d99" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "actor_type"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "hourly_rate"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "iam_users" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "fullName" character varying`);
        await queryRunner.query(`ALTER TABLE "iam_users" ADD "passwordHash" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "csk_tickets"`);
        await queryRunner.query(`DROP TABLE "fin_payments"`);
        await queryRunner.query(`DROP TABLE "auth_credentials"`);
        await queryRunner.query(`DROP TABLE "sys_digital_signatures"`);
        await queryRunner.query(`DROP TABLE "prj_baselines"`);
        await queryRunner.query(`DROP TABLE "prj_members"`);
        await queryRunner.query(`DROP TABLE "sys_audit_logs"`);
        await queryRunner.query(`DROP TABLE "sys_notifications"`);
        await queryRunner.query(`DROP TABLE "tms_timesheets"`);
        await queryRunner.query(`DROP TABLE "fin_invoices"`);
        await queryRunner.query(`DROP TABLE "prj_tasks"`);
        await queryRunner.query(`DROP TABLE "prj_projects"`);
        await queryRunner.query(`DROP TABLE "sls_contracts"`);
        await queryRunner.query(`DROP TABLE "sls_quotations"`);
        await queryRunner.query(`DROP TABLE "sys_branches"`);
    }

}
